name: check-for-version-update
description: Guard - Update version if source files have changed

inputs:
  path:
    description: path to source folder
    required: true

runs:
  using: composite
  steps:
    - name: Get changed source files
      id: changed-source
      uses: tj-actions/changed-files@v29

    - name: Check if version has been updated
      id: check
      uses: DevExpress/github-actions/verify-version-change@main
      with:
        path: ${{ inputs.path }}

    - name: Check changes
      shell: bash
      env:
        source-path: ${{ inputs.path }}/src/
      if: ${{ contains(steps.changed-source.outputs.all_changed_files, env.source-path) &&
        steps.check.outputs.changed == 'false' }}
      run: |
        echo "Please, update version in ${{ inputs.path }}/package.json"
        exit 1
