name: verify-version-changed
description: Verify changed package version

inputs:
  path:
    description: Package path
    required: false
    default: .

runs:
  using: node16
  main: dist/index.js

outputs:
  changed:
    description: true if version was bumped
  version:
    description: new version
